### ISSUE TITLE
Have two words for "Layer"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#13]
> - Layers are things you define in a style
> - Layers are also things in a datasource
> 
> Two concepts deserve two words

_originally posted by @tmcw as https://github.com/mapbox/mapbox-gl-js/issues/1237_

cc @peterqliu @anandthakker @nickidlugash @jfirebaugh @mourner @ansis @springmeyer @yhahn @bhousel

**Comment by lucaswoj** [comment]
This is a complex issue.

Studio and the APIs currently use `subset` to refer to a "things in a datasource"

mapbox-gl-js, mapbox-gl-native, mapbox-gl-style-spec, exiting mapbox styles, and the vector tile spec use `source-layer` to "things in a datasource"

In my opinion, studio and the APIs should change to match the convention of calling "things in a datasource" `source-layer`. The "source" modifier is an acceptable differentiator between types of things.

**Comment by jfirebaugh** [comment]
Both things are called "layers" in their respective specifications.
- [Vector tile layers](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers)
- [Style layers](https://www.mapbox.com/mapbox-gl-style-spec/#layers)

It's unlikely that we're going to rename either of these at the specification level, and I believe that introducing terms different than the underlying specification confuses, rather than clarifies, the issue. Let's use "source layer" and "style layer" where explicit disambiguation is necessary.

**Comment by tmcw** [comment]
cc @mapbox/appbox is this okay from a studio perspective, could we do a studio-wide rename?

**Comment by lyzidiamond** [comment]
I'm okay with source layer and style layer, so long as we are consistent.

**Comment by scothis** [comment]
> is this okay from a studio perspective, could we do a studio-wide rename?

Doable. There are a couple tight places where we'll need to manually nudge the UI.

> I'm okay with source layer and style layer, so long as we are consistent.

agreed
