### ISSUE TITLE
Create a feature comparison between the GL libraries

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#16]
I'm interested in building a feature support table, a la [node.green](http://node.green/) or [caniuse.com](http://caniuse.com/), that tracks the implementation of features across GL JS, GL Native, iOS SDK, Android SDK, etc. This information currently only exists as institutional knowledge. The table would include
- support for map APIs (runtime styling API, runtime source API, annotations APIs, etc)
- support for style spec features (source types, property functions, zoom & property functions, etc)
- ??

cc @yhahn @jfirebaugh @1ec5 @tmcw @scothis @mourner

**Comment by 1ec5** [comment]
Yes, we’re getting to the point where we really need something like this, especially when it comes to features that are implemented purely in platform-specific code, such as view-backed annotations.

As a first step, let’s make the issue labels in each repository more clear. We have a lot of open issues for porting or adapting a feature from one library to another, and we can use the labels to build a table. GL JS should have these labels instead of just `mapbox.js parity`:
- `mapbox.js parity`
- `gl-native core parity`
- `gl-native SDK parity`

The gl-native `parity` label should be split into:
- `legacy SDK parity`
- `gl-js parity`
- `Android SDK parity`
- `iOS SDK parity`
- `OS X SDK parity`
- `Qt SDK parity`
- `Node.js SDK parity`

**Comment by scothis** [comment]
I'd love if we could write automated tests to keep the table up to date, but given the number of platforms and language bindings, that's probably not feasible.

**Comment by jfirebaugh** [comment]
We could track support of source types, style properties, and data-driven function support in the style-spec .json, and then generate nice output for `mb-pages`. Spitballing:

```
    "icon-pitch-alignment": {
      ...
      "base-support": {
        "js": "0.20.0",
        "ios": "3.4.0",
        "android": "4.2.0"
      },
      "dds-support": {
        "js": "0.21.0"
      }
    },
```

**Comment by lucaswoj** [comment]
> I'd love if we could write automated tests to keep the table up to date, but given the number of platforms and language bindings, that's probably not feasible.

Idea: we can link all "not supported" 🔴 cells to GitHub issues. When the GitHub issue closes, the cell changes to "supported" ✅. 

EDIT we could optionally add a manual review step in there

**Comment by jfirebaugh** [comment]
Linking a GitHub issue for incomplete features is fine, but they have some deficiencies as a "supported" status indicator for end users: issues get closed before the feature is shipped in any production release, and it can be hard to decipher from an issue what the minimum version requirement is. I'd rather go with updating minimum supported versions manually as part of the release process.

**Comment by 1ec5** [comment]
I started an API feature comparison table [on the OpenStreetMap Wiki](http://wiki.openstreetmap.org/wiki/Mapbox_GL) in the course of enumerating Mapbox GL’s feature set. (The point of this exercise was to replace a lot of inaccurate or missing information about this project on that wiki.) I deliberately kept the table high-level for maintainability, but feel free to expand it or use it as the basis for a more detailed chart.

**Comment by bleege** [comment]
This is going to be very helpful.  Thanks for proposing this @lucaswoj and for @jfirebaugh running with this in https://github.com/mapbox/mapbox-gl-style-spec/pull/465.
