### ISSUE TITLE
Rendering support for 3D file formats? 

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/DEPRECATED-mapbox-gl#17]
We are adding support for [simple extrusions](https://github.com/mapbox/mapbox-gl-style-spec/issues/456). For buildings, there are some complex and high-profile landmarks that can't be rendered accurately with simple extrusion:

![eiffel-tower](https://cloud.githubusercontent.com/assets/5607844/16136340/b62eef22-33f7-11e6-9982-736ec86cbd42.png)
_Haiii, Eiffel Tower._

For these features, it seems like we would want to include 3D models. How would/could this work? How much of a lift is this? 

/cc @lbud @ajashton @mapbox/gl

**Comment by mourner** [comment]
I think full 3D model support is too big of a bluesky lift, but what we could do for landmarks is implementing a few common roof types that OSM supports: http://wiki.openstreetmap.org/wiki/Simple_3D_buildings

It's a considerably lift but not nearly as intimidating as 3D models.

**Comment by nickidlugash** [comment]
@mourner thanks for the feedback! I opened a separate ticket for roofs: https://github.com/mapbox/mapbox-gl/issues/18

I'd still be very interested in hearing any ideas about what it would take to implement full 3D model support, even if it is bluesky and not feasible for right now. This will help the whole team can plan around our 3D play.

**Comment by svcninja** [comment]
👍

**Comment by popovae** [comment]
Hi,

As mentioned before - "there are some complex and high-profile landmarks that can't be rendered accurately with simple extrusion" and the best way I can see to render them correctly is to add ability to render 3D model on the clients-side. Adding a new source type for OBJ files will solve this problem...will it work with you?

I know the MapBox team will probably just ignore this comments, but lets be honest - the current Mapbox 3D view just s@x comparing to Google or even OSM Buildings! Look at the screenshot of the Eiffel Tower... 
And also - there is still no solution to add the roofs to the buildings, really!? Here is the thing - 95% of the buildings roofs are not flat))

One more thing - I know it is hard to "have a look around yourself" when you are fully into something, but it'll be great if you will be able to listen to some useful comments about your product...as some of your latest implementation just don't make any sense in most business cases...

**Comment by tmcw** [comment]
Hi Andrei,

Thanks for the feedback! We do, indeed, read comments - hundreds a day.

But I have a hard time finding anything constructive about your criticism and I'm finding a lot of it to be hyperbolic and abrasive. Your previous [issue](https://github.com/mapbox/mapbox-gl-js/issues/3318) was responded to promptly, within the day, even though it, too, had called our work 'useless and really buggy'. The team is working on gigantic problems right now, like text shaping, 3D buildings, arbitrary functions in filters, and a host of performance improvements, and insultingly shouting at them to fix this problem won't make the problem get fixed any faster. It'll only make people annoyed.

Again, thanks for your thoughts and we do hope that you contribute in the future, but this is a space for constructive thinking, not ranting: please consider that there are humans on the other side of the internet, and that they are not motivated by abuse.

- Tom

**Comment by popovae** [comment]
Hi Tom @tmcw,

First of all thank you for your response! Yes, indeed it is a little keen comment on my behalf but unfortunately there are some reasons for that...

The issue you are referring to is open from October - but no solution found till now. It is not really a bug, but at the same time it has a particular impact on the whole idea of clustering - making it impossible to implement this function in most of use cases...hope you will agree.

I will explain what I was trying to say within all this comment above - you definitely put a huge amount of afford in developing new functions, improvement and so on. But some of them are not "quite finished" at the end and are left untouched for indefinite amount of time... The devs who develop them are simply switching for another tasks leaving the users with the only option - to find the workaround themselves... The most unpleasant in this situation is that when someone is pointing on the shortcoming - it is simply ignored. Also, it is hard to believe that implementing some of the functions are "too big of a bluesky lift" considering they were implemented years ago in other projects.

Here is one more example - you implemented the great feature - Datasets. It is for sure the easiest and user-friendliest way to add some data to a custom map. The question is - can I add new building/road instead of existing in OSM (streetsv7)? Think the answer is NO, but the reason lies in something the users asked for several times and is still missing in Mapbox - ID of each object on map. Knowing the ID will allow much more then that - linking external datasets with map object, filtering objects on map and etc

Overall - if you consider my comments as an abuse - please accept my apologies. But, at the same time, please consider that probably most of the users will be happy with fixed bugs in the old functions then new "text shaping", elevations or something else...

**Comment by tmcw** [comment]
Hi Andrei,

Thanks for the response.

One thing you might want to look into is the other issues I mentioned. An issue like text-shaping for instance, which you can read about [on this ticket](https://github.com/mapbox/mapbox-gl/issues/4) which has 44 replies, is vitally important to other people. Without text shaping, we don't have support for Arabic or Hebrew. Commenters have stressed the geographical and cultural importance of the issue, and they're right: messing up the rendering of placenames that aren't in English is a really bad problem and it's easier for us to live with it here at Mapbox because not many of us speak Hebrew or Arabic as a first language.

Relative to making maps available in people's first languages, is drawing nice 3D buildings obviously more important to everyone? Would our Hebrew-reading users really prefer a slanted roof rather a readable map? Similarly, you can think of other issues in the same light. If you take the time to understand the actual issues, the work that's required to fix them, and the reason why they're important to the people who rally for them, you hopefully won't jump to the conclusion that they're obviously less important than the thing you want.

I think you'll find similar responses on each issue: for each issue, there are excited and angry and enthusiastic people, just like you, but with different priorities. Like you, they believe that their priorities are extremely important, and they're right. But we're in the place where we have to take all of these priorities and juggle them into something that resembles a roadmap, and only a few things can be top priority at a time.

This is where the phrase 'simply ignored' comes up, and it's not a very accurate description. Everyone reads all issues, and we all prioritize our time. Assuming that things that aren't currently the top priority or that are scheduled for work in the future are 'simply ignored' is making an inappropriate assumption about what we're thinking and how we think.

- Tom

**Comment by popovae** [comment]
Hi Tom,

Agreed - solving issue you know about for 12 mont - it is a priority task! 
And yes, I agree that prioritising tasks is really important!
And no - I dont think this task is super-high priority! Just a good idea, for us to be able to create nice 3D maps with potentially no limitations and for you - to get rid of old OSM specifications, roof types as an example...win-win;)

Overall - It is exactly the thing I was talking about here - if you have a lot (or a few) bugs in 2D, why to start new complicated tasks you can not possibly handle...make more "open tickets"? At the end of the day - huge amount of tickets in 2D and now the unfinished (in my opinion) 3D... 

For sure I understand that Mapbox has to handle all this "investor-funding entourage", but the users do matter too, "understand" but not "read" the suggestions;)

**Comment by jingsam** [comment]
Hi, @popovae , I recommend  you to read the new book [Polite Technology](http://polite.technology/preview/) writen by Tom.

I think there are 3 ways to get what you want:
1. Acquire Mapbox.  Because you are the boss, I guess they would implement whatever you want.
2. Become one of their most important consumers like Foursqure, Airbub, or Github. On this circumstance, you can "push" them to solve your problem.
3. Contributing than complaining.  If you think some issues really important to you, just dig into the source code and send PRs. Don't want to dirty your hands? Hire someone do it for you!

**Comment by popovae** [comment]
Hi, @jingsam 
))) Thank you for suggestion) 
1st - definitely too late already)
2nd - think Airbnb is using google.maps))) And for sure I wouldn't recommend any project to be dependent on MB resources and etc
3rd - that what we are doing - using Mapbox as a nice map layer for some of the projects and the rest is our own layers)) The question now is - at some point, I see only problems using Mapbox...and f@ck - I was the one who was running around everyone pitching to switch to MB from GM)))

**Comment by jfirebaugh** [comment]
Thanks all. I think everyone has had ample chance to voice their opinion here. It seems further conversation on this topic is not likely to be productive, so I'm going to lock the issue.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3996
