### ISSUE TITLE
What is the correct behavior for a source with a polyline paired with a fill style layer

### ISSUE THREAD

**Issue by boundsj** [mapbox/DEPRECATED-mapbox-gl#31]
A recent support request (for iOS) noted that we don't prohibit a developer from creating a GeoJSON source that contains a polyline and then using a fill style layer to style it. However, on iOS and Android, this combination results in some undesirable clipping behavior at high zoom levels (see screenshot below).

The solution is to use polygons with fill layers. However, should we better support the problematic combination noted above or do something mopre to warn developers that this is not supported?

#### Source with an polyline styled with a fill layer -- zooming in illustrates the reported issue

![screenshot 2016-12-08 14 23 05](https://cloud.githubusercontent.com/assets/63186/21030137/db6d73a6-bd51-11e6-924f-9bc405b75696.png)

cc @1ec5 @cammace @jfirebaugh

**Comment by jfirebaugh** [comment]
In general, we have not defined specific behavior for odd or nonsensical combinations of layer type and source geometry such as fill layer + LineString. In fact there's a [test case](https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/geojson/inline-linestring-fill/style.json) for this particular combination that's disabled because the current behavior is arbitrary and not consistent between -js and -native.

**Comment by 1ec5** [comment]
We could explicitly state in line layer documentation that using a linestring (polyline) feature with the layer results in undefined behavior. But I’m not sure there’s much we can do about the very plausible scenario where a developer fat-fingers “polyline” when they meant “polygon” because code completion autoselects the more recently used option between the two.

**Comment by mourner** [comment]
I'd vote for making this an error (tracked by the style validator) in the next style spec version.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/4002
